### ISSUE TITLE
iNFT, Scarcity of mathematics  identifiable NFT, template part

### ISSUE THREAD

**Issue by ff13dfly** [fxgst/azle-react#6]
[iNFT ICP template project](https://github.com/ff13dfly/iNFT-ICP)

Description: iNFT, Identifiable NFT, is an efficient method of generating NFTs based on mathematical randomness, producing visually distinguishable results.
At this hack house, try to storage the definition of iNFT on chain and review.

Track: Fully on-chain dapps
Team participants: @ff13dfly

Mainnet canister link: https://i6tq5-ziaaa-aaaap-ahaia-cai.icp0.io

Feedback:
Great concept that treating everything as contract on chain.
Easy for starter to start coding.

**Comment by ff13dfly** [comment]
> [iNFT ICP template project](https://github.com/ff13dfly/iNFT-ICP)
> 
> Description: iNFT, Identifiable NFT, is an efficient method of generating NFTs based on mathematical randomness, producing visually distinguishable results. At this hack house, try to storage the definition of iNFT on chain and review.
> 
> Track: Fully on-chain dapps Team participants: @ff13dfly
> 
> Mainnet canister link: https://i6tq5-ziaaa-aaaap-ahaia-cai.icp0.io
> 
> Feedback: Great concept that treating everything as contract on chain. Easy for starter to start coding.

Sorry about the issue, join the HK hack house.

**Comment by fxgst** [comment]
This is the wrong place for submissions. Please submit [here](https://github.com/ICP-Hacker-House/ICP_Hacker_House_HK/issues/new)
